---
- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set logging
  community.general.ufw:
    logging: 'on'

# Sometimes it is desirable to let the sender know when traffic is
# being denied, rather than simply ignoring it. In these cases, use
# reject instead of deny. In addition, log rejected connections:
- name: reject 
  community.general.ufw:
    rule: reject
    port: auth
    log: true
    
# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details. Typical usage is:
- name: limit ssh
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow all access to tcp port 7890 NIS
  community.general.ufw:
    rule: allow
    port: '7890'
    proto: tcp

- name: Allow all access to tcp port 7891 HTTPS
  community.general.ufw:
    rule: allow
    port: '7880'
    proto: tcp    
    
- name: Allow all access to tcp port 7880 Servant
  community.general.ufw:
    rule: allow
    port: '7880'
    proto: tcp

- name: Allow all access to tcp port 7778 Websocket
  community.general.ufw:
    rule: allow
    port: '7778'
    proto: tcp