$ANSIBLE_VAULT;1.2;AES256;nem
61383562343265653936343336316333323936366562306364336334366239646363646236353032
3535643365366665333061373066616666656466366562330a663436366466653038653539323662
30383965393032323134326439353536306163646132303164306438333438383838393639336334
3832323034333966660a636163653262346366366536653963373332383462326164343433306639
62666237393065333837393432656236666237383865626533303837323339623431623838666630
36613363656565623834303364626531306162616532303664653437613363623334666565643164
31633737356363356130306634313232366364333935643866353230613436663766643131353932
34653237643965306462306536376536316232646633613131393437343965623566383130343466
64623732656537306531303032306333343461346564623030623039373866366634653537646634
38326434353661666531636463363333303961393366613639353365386562393338616465663237
306630366662326133633266316636336264
